#!/usr/bin/env python3
"""
make_pdf.py (size-optimized)

Key options:
  --max-images N        Limit to first N images (default: 0 => no limit)
  --max-width PX        Resize images to this max width (preserve aspect), default 1200
  --jpeg-quality Q      JPEG quality for intermediate conversion (1-100), default 60
  --cover               generate a cover (keeps it small)
  --quality {screen,web,printer} for Ghostscript compression (default: screen)

Usage:
  python3 make_pdf.py --cover --lang both --quality screen --max-images 30 --max-width 1200 --jpeg-quality 60 --out fanfan_final.pdf
"""
from __future__ import annotations
import argparse
import sys
import os
import shutil
import subprocess
from pathlib import Path
from typing import List, Tuple
import tempfile

try:
    from PIL import Image, ImageDraw, ImageFont
except Exception:
    print("Pillow required: pip install pillow")
    raise

try:
    import img2pdf
except Exception:
    print("img2pdf required: pip install img2pdf")
    raise

try:
    from natsort import natsorted
except Exception:
    def natsorted(x):
        return sorted(x)

DEFAULT_IMAGES_DIR = "KRS规格书"
SUPPORTED_IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".tif", ".tiff", ".bmp", ".webp"}

def find_images_in_dir(dirpath: Path) -> List[Path]:
    if not dirpath.exists() or not dirpath.is_dir():
        return []
    imgs = [p for p in dirpath.iterdir() if p.suffix.lower() in SUPPORTED_IMAGE_EXTS and p.is_file()]
    return natsorted(imgs)

def text_size_compat(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont) -> Tuple[int, int]:
    if hasattr(draw, "textbbox"):
        bbox = draw.textbbox((0, 0), text, font=font)
        return bbox[2] - bbox[0], bbox[3] - bbox[1]
    if hasattr(draw, "textsize"):
        return draw.textsize(text, font=font)
    if hasattr(font, "getsize"):
        return font.getsize(text)
    return (len(text) * getattr(font, "size", 24) // 2, int(getattr(font, "size", 24) * 1.2))

def make_cover_image(
    title_zh: str,
    title_en: str,
    logo_path: Path | None,
    lang: str = "both",
    size=(1200, 1700),  # smaller cover size for smaller PDF
    title_font_size=36,
    subtitle_font_size=20,
    bg_color=(255, 255, 255),
) -> Path:
    W, H = size
    im = Image.new("RGB", (W, H), color=bg_color)
    draw = ImageDraw.Draw(im)

    def load_font(preferred_size):
        candidates = [
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
            "/Library/Fonts/Arial.ttf",
            "/System/Library/Fonts/Supplemental/Arial.ttf",
            str(Path(__file__).parent / "fonts" / "DejaVuSans.ttf"),
        ]
        for c in candidates:
            try:
                if Path(c).exists():
                    return ImageFont.truetype(c, preferred_size)
            except Exception:
                continue
        return ImageFont.load_default()

    font_title = load_font(title_font_size)
    font_sub = load_font(subtitle_font_size)

    y = int(H * 0.15)

    if logo_path and logo_path.exists():
        try:
            logo = Image.open(logo_path).convert("RGBA")
            max_logo_w = int(W * 0.25)
            wratio = max_logo_w / logo.width
            logo_h = int(logo.height * wratio)
            logo = logo.resize((max_logo_w, logo_h), Image.LANCZOS)
            im.paste(logo, ((W - max_logo_w) // 2, 20), logo if logo.mode == "RGBA" else None)
            y = 20 + logo_h + 20
        except Exception:
            pass

    def draw_centered_text(text: str, font: ImageFont.FreeTypeFont, start_y: int, line_spacing: int = 6):
        nonlocal draw, W
        lines = text.splitlines() if text else [""]
        cur_y = start_y
        for line in lines:
            w, h = text_size_compat(draw, line, font)
            draw.text(((W - w) / 2, cur_y), line, fill="black", font=font)
            cur_y += h + line_spacing
        return cur_y

    if lang == "zh":
        title_text = title_zh
        sub_text = ""
    elif lang == "en":
        title_text = title_en
        sub_text = ""
    else:
        title_text = title_zh
        sub_text = title_en

    y_after = draw_centered_text(title_text, font_title, y)
    if sub_text:
        draw_centered_text(sub_text, font_sub, y_after + 8)

    footer_font = load_font(12)
    footer = "Generated by make_pdf.py"
    fw, fh = text_size_compat(draw, footer, footer_font)
    draw.text((W - fw - 20, H - fh - 20), footer, fill=(90, 90, 90), font=footer_font)

    tmpdir = Path(tempfile.gettempdir())
    cover_path = tmpdir / f"cover_{os.getpid()}.jpg"
    im.save(cover_path, format="JPEG", quality=70, optimize=True)
    print(f"[+] Generated small cover: {cover_path}")
    return cover_path

def prepare_images_for_pdf(image_paths: List[Path], tmpdir: Path, max_width: int, jpeg_quality: int, max_images: int) -> List[str]:
    """
    Resize/convert images to JPEGs saved in tmpdir; return list of file paths (strings).
    If max_images>0, limit to first max_images.
    """
    prepared = []
    to_use = image_paths[:max_images] if max_images and max_images > 0 else image_paths
    for p in to_use:
        try:
            im = Image.open(p).convert("RGB")
            if max_width and im.width > max_width:
                h = int(im.height * (max_width / im.width))
                im = im.resize((max_width, h), Image.LANCZOS)
            outp = tmpdir / (p.stem + ".jpg")
            im.save(outp, format="JPEG", quality=jpeg_quality, optimize=True)
            prepared.append(str(outp))
        except Exception as e:
            print(f"Warning: failed to process {p}: {e}")
    return prepared

def build_pdf_from_images(image_files: List[str], output_pdf: Path) -> None:
    if not image_files:
        raise ValueError("No images to convert to PDF.")
    try:
        with open(output_pdf, "wb") as f:
            f.write(img2pdf.convert(image_files))
    except Exception as e:
        print("Error creating PDF:", e)
        raise
    print(f"[+] Created PDF: {output_pdf}")

def compress_pdf_with_ghostscript(input_pdf: Path, output_pdf: Path, quality: str = "screen") -> bool:
    quality_map = {"screen": "/screen", "web": "/ebook", "printer": "/printer"}
    preset = quality_map.get(quality, "/screen")
    gs_cmd = shutil.which("gs") or shutil.which("ghostscript")
    if not gs_cmd:
        print("No Ghostscript found; skipping compression.")
        return False
    cmd = [
        gs_cmd,
        "-sDEVICE=pdfwrite",
        "-dCompatibilityLevel=1.4",
        "-dPDFSETTINGS=" + preset,
        "-dNOPAUSE",
        "-dQUIET",
        "-dBATCH",
        f"-sOutputFile={str(output_pdf)}",
        str(input_pdf),
    ]
    try:
        subprocess.check_call(cmd)
        print(f"[+] Compressed PDF to: {output_pdf}")
        return True
    except subprocess.CalledProcessError as e:
        print("Ghostscript compression failed:", e)
        return False

def parse_args():
    p = argparse.ArgumentParser(description="Create a size-optimized PDF from images")
    p.add_argument("--cover", action="store_true")
    p.add_argument("--lang", choices=("zh", "en", "both"), default="both")
    p.add_argument("--logo", type=str, default=None)
    p.add_argument("--quality", choices=("screen","web","printer"), default="screen", help="Compression preset (screen smallest)")
    p.add_argument("--out", type=str, default="fanfan_final.pdf")
    p.add_argument("--images-dir", type=str, default=DEFAULT_IMAGES_DIR)
    p.add_argument("--max-images", type=int, default=0, help="Limit to first N images (0 = no limit)")
    p.add_argument("--max-width", type=int, default=1200, help="Max width in px to resize images")
    p.add_argument("--jpeg-quality", type=int, default=60, help="JPEG quality 1-100 for intermediate images")
    return p.parse_args()

def main():
    args = parse_args()
    images_dir = Path(args.images_dir)
    out_pdf = Path(args.out).resolve()

    images = find_images_in_dir(images_dir)
    if not images:
        print(f"No images found in {images_dir}")
        sys.exit(1)

    tmpdir = Path(tempfile.mkdtemp(prefix="krs_pdf_"))
    tmp_files = []
    try:
        prepared_files: List[str] = []

        if args.cover:
            logo_p = Path(args.logo) if args.logo else None
            cover_img = make_cover_image("KRS 规格书", "KRS Specification", logo_p, lang=args.lang)
            # ensure cover is resized to max_width
            cover_path = Path(cover_img)
            prepared_cover = prepare_images_for_pdf([cover_path], tmpdir, args.max_width, args.jpeg_quality, 1)
            prepared_files.extend(prepared_cover)
            tmp_files.append(cover_path)

        # Prepare images with resizing & JPEG conversion and optional limit
        prepared = prepare_images_for_pdf(images, tmpdir, args.max_width, args.jpeg_quality, args.max_images)
        prepared_files.extend(prepared)

        if not prepared_files:
            print("No prepared images for PDF.")
            sys.exit(1)

        # Build pdf from prepared JPEGs
        build_pdf_from_images(prepared_files, out_pdf)

        # Compress with Ghostscript (aggressive)
        compressed = out_pdf.with_suffix(".compressed.pdf")
        if compress_pdf_with_ghostscript(out_pdf, compressed, args.quality):
            shutil.move(str(compressed), str(out_pdf))
    finally:
        # cleanup tmpdir
        try:
            shutil.rmtree(tmpdir)
        except Exception:
            pass
        for t in tmp_files:
            try:
                if t.exists():
                    t.unlink()
            except Exception:
                pass

    print("[+] Done. Output:", out_pdf)

if __name__ == "__main__":
    main()
